In [2]:
import pandas as pd
import numpy as np

In [4]:
# READING BHAV.
bhav = pd.read_csv('bhav21APR2023.csv')
bhav = bhav.drop(['TIMESTAMP', 'ISIN', 'Unnamed: 13'], axis= 1)
bhav

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TOTALTRADES
0,182D150623,TB,99.00,99.00,99.00,99.00,99.00,98.48,500,4.950000e+04,1
1,182D220923,TB,96.71,97.17,96.71,96.95,96.95,96.59,1400,1.357200e+05,3
2,20MICRONS,EQ,82.55,85.30,82.55,83.80,83.80,83.80,70010,5.908412e+06,1248
3,21STCENMGM,EQ,19.70,19.70,19.70,19.70,19.70,20.10,1657,3.264290e+04,9
4,360ONE,EQ,409.85,412.20,404.25,407.00,407.45,409.85,146745,5.962876e+07,5895
...,...,...,...,...,...,...,...,...,...,...,...
2367,ZOTA,EQ,281.00,289.00,280.05,282.85,284.45,280.95,7109,2.021482e+06,518
2368,ZUARI,EQ,132.90,134.85,129.85,130.70,130.50,131.95,75493,9.933307e+06,2080
2369,ZUARIIND,EQ,125.15,127.95,124.05,125.95,124.50,126.20,35109,4.431914e+06,843
2370,ZYDUSLIFE,EQ,512.00,520.65,509.15,518.75,516.80,513.70,1112338,5.761714e+08,26192
2371,ZYDUSWELL,EQ,1510.05,1547.95,1510.00,1529.65,1528.00,1508.05,14185,2.169377e+07,3938

In [5]:
# choosing the trades that have.
bhav = bhav[(bhav['SERIES']=='EQ') & (bhav['TOTALTRADES']> 50000)]
bhav

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TOTALTRADES
64,ADANIENT,EQ,1846.00,1853.25,1796.05,1803.00,1802.00,1842.90,2090833,3.796946e+09,87940
67,ADANIPOWER,EQ,200.00,200.50,193.60,199.25,197.70,195.80,11239848,2.221803e+09,73836
184,ASHOKLEY,EQ,138.90,138.90,135.80,136.25,136.45,138.90,8710613,1.189968e+09,61992
203,AUBANK,EQ,680.45,680.85,656.85,665.95,665.00,679.40,3742874,2.491298e+09,69279
220,AXISBANK,EQ,870.80,873.85,857.50,864.20,860.70,868.75,15520786,1.345477e+10,117031
244,BAJFINANCE,EQ,5913.00,5945.00,5828.00,5937.90,5938.00,5912.70,643101,3.797579e+09,55012
300,BHARTIARTL,EQ,769.60,775.25,764.45,765.20,767.00,772.30,4524208,3.469725e+09,85326
317,BLS,EQ,168.35,179.25,166.30,178.15,177.75,167.70,6527106,1.144170e+09,125169
325,BORORENEW,EQ,480.10,508.75,478.00,499.55,496.00,481.00,2537305,1.272658e+09,66432
327,BPCL,EQ,343.80,348.90,342.60,346.20,345.65,343.70,3276344,1.136757e+09,50785
396,CIPLA,EQ,903.00,918.55,903.00,915.05,915.90,904.00,3481218,3.173146e+09,51597
444,CYIENT,EQ,1140.00,1193.70,1126.15,1159.65,1154.90,1091.25,6026418,6.991028e+09,146004
446,DABUR,EQ,525.40,528.35,523.70,525.15,525.00,525.30,1242615,6.538322e+08,58391
473,DELHIVERY,EQ,337.15,363.50,335.05,357.25,350.00,337.10,5079234,1.795595e+09,72575
507,DLF,EQ,414.30,414.30,402.00,406.05,405.60,414.45,5194549,2.110577e+09,55266
559,EICHERMOT,EQ,3240.00,3259.95,3194.10,3200.70,3204.35,3246.95,443737,1.428000e+09,52517
607,FACT,EQ,326.00,344.75,320.50,331.75,331.30,325.00,3892287,1.307827e+09,50759
613,FDC,EQ,272.95,296.95,272.00,290.00,288.00,271.05,3060741,8.890582e+08,51744
699,GODREJCP,EQ,972.10,990.75,972.10,987.15,987.90,975.15,1384698,1.363648e+09,56651
768,HCLTECH,EQ,1054.00,1074.00,1037.75,1048.95,1048.20,1037.50,7708194,8.095035e+09,190714
769,HDFC,EQ,2735.50,2763.55,2735.40,2759.40,2758.70,2743.00,1719725,4.726244e+09,93216
772,HDFCBANK,EQ,1669.00,1676.95,1663.25,1674.60,1672.00,1671.90,10064309,1.680839e+10,159632
775,HDFCLIFE,EQ,536.00,541.25,511.40,513.30,513.50,530.25,4452849,2.319137e+09,94884
795,HERANBA,EQ,327.10,374.90,327.10,361.75,361.00,327.10,1743777,6.345980e+08,57327
809,HINDALCO,EQ,430.00,430.85,419.00,422.35,422.60,429.85,5139533,2.170297e+09,83610
816,HINDUNILVR,EQ,2492.00,2509.50,2485.65,2497.95,2499.85,2492.60,1206288,3.010086e+09,83359
873,ICICIBANK,EQ,894.55,900.70,882.40,885.65,887.60,894.40,29578071,2.638556e+10,191343
893,ICICIPRULI,EQ,457.00,462.85,438.60,444.10,443.95,455.70,8724739,3.909071e+09,128717
901,IDEA,EQ,6.15,6.65,6.15,6.45,6.45,6.05,326277787,2.108340e+09,83952
978,INDUSINDBK,EQ,1126.20,1135.75,1108.35,1116.35,1114.20,1126.20,1894300,2.123871e+09,60760
979,INDUSTOWER,EQ,138.25,144.70,137.85,139.10,139.10,137.70,17513812,2.478189e+09,82603
985,INFY,EQ,1228.10,1233.25,1220.00,1227.35,1227.00,1223.40,8691352,1.065954e+10,209013
1027,ITC,EQ,400.30,409.00,399.05,408.25,408.00,400.30,14252204,5.782075e+09,143707
1155,KOTAKBANK,EQ,1882.00,1903.65,1877.15,1893.65,1891.00,1884.00,1671341,3.169186e+09,59616
1222,LIBERTSHOE,EQ,276.00,300.90,273.50,277.60,274.35,267.00,3712389,1.066895e+09,63607
1244,LT,EQ,2240.15,2243.00,2202.00,2215.20,2214.90,2232.75,1009316,2.234792e+09,56949
1246,LTIM,EQ,4162.15,4213.90,4132.20,4170.85,4164.00,4152.85,480473,1.999048e+09,60045
1321,MAXHEALTH,EQ,466.60,467.25,451.15,453.45,452.45,465.40,1280680,5.823297e+08,61328
1436,NAZARA,EQ,535.75,587.50,533.95,564.90,560.00,531.80,6615575,3.794015e+09,112695
1509,NTPC,EQ,169.65,169.95,168.40,169.70,169.65,169.70,6672391,1.128459e+09,52014
1522,NYKAA,EQ,124.00,124.25,120.15,120.60,121.10,123.75,17843321,2.168883e+09,77620
1726,RELIANCE,EQ,2350.65,2361.00,2336.40,2349.00,2351.00,2346.05,3529236,8.289102e+09,151695
1777,RVNL,EQ,78.95,79.75,76.70,77.50,76.90,77.10,26606072,2.087272e+09,64736
1824,SBILIFE,EQ,1136.60,1136.60,1103.35,1106.55,1108.50,1128.85,835506,9.312397e+08,50659
1825,SBIN,EQ,545.00,546.40,539.70,543.15,542.30,544.80,22599418,1.225680e+10,188920
2122,TATAINVEST,EQ,2064.00,2243.25,2059.55,2157.30,2160.00,2064.85,793639,1.742164e+09,53076
2124,TATAMOTORS,EQ,476.70,476.70,467.20,471.20,471.20,476.80,8478118,3.990829e+09,107355
2127,TATASTEEL,EQ,108.00,108.10,105.35,106.15,106.10,108.00,37638506,3.991843e+09,155242
2138,TCS,EQ,3110.00,3164.45,3100.80,3160.85,3159.00,3104.80,1929184,6.049023e+09,98768
2143,TECHM,EQ,1014.30,1019.60,993.85,998.75,998.85,1021.80,4269272,4.271770e+09,157323
2207,TVSMOTOR,EQ,1128.30,1130.50,1084.00,1092.95,1093.20,1127.95,2877179,3.157755e+09,70791
2271,VEDL,EQ,279.60,279.85,276.00,276.75,276.20,279.60,4599260,1.276126e+09,51589
2366,ZOMATO,EQ,54.30,56.75,54.10,56.05,55.60,54.20,106707937,5.952760e+09,127296

In [56]:
data = pd.read_csv("SBIN.csv")
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-01-01,274.899994,280.000000,274.399994,279.399994,272.589966,24531791
1,2021-01-04,281.850006,283.899994,277.750000,281.049988,274.199707,31450608
2,2021-01-05,278.049988,282.450012,277.000000,281.750000,274.882690,27393072
3,2021-01-06,283.000000,289.149994,281.399994,285.049988,278.102234,40765708
4,2021-01-07,289.000000,291.799988,287.000000,287.700012,280.687683,30546600
...,...,...,...,...,...,...,...
565,2023-04-17,528.000000,545.000000,528.000000,544.000000,544.000000,32476990
566,2023-04-18,545.349976,548.500000,540.500000,545.849976,545.849976,22283456
567,2023-04-19,544.000000,547.500000,538.250000,540.299988,540.299988,21156372
568,2023-04-20,541.200012,545.450012,536.650024,544.799988,544.799988,25588577
569,2023-04-21,545.000000,546.400024,539.700012,543.150024,543.150024,22599418

In [7]:
# choosing the trades that have.
bhav = bhav[bhav[]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3808537584.py, line 2)

In [63]:
# calculating moving averages
def SMA(col: pd.Series, period: int = 50):
    return col.rolling(period).mean()

In [64]:
# calculate moving average
data["MA20"] = SMA(data['Close'], 20)
data['MA50'] = SMA(data['Close'])
data["MA200"] = SMA(data['Close'], 200)
data

,Date,Open,High,Low,Close,Adj Close,Volume,MA20,MA50,MA200,RSI
0,2021-01-01,274.899994,280.000000,274.399994,279.399994,272.589966,24531791,NaN,NaN,NaN,NaN
1,2021-01-04,281.850006,283.899994,277.750000,281.049988,274.199707,31450608,NaN,NaN,NaN,NaN
2,2021-01-05,278.049988,282.450012,277.000000,281.750000,274.882690,27393072,NaN,NaN,NaN,NaN
3,2021-01-06,283.000000,289.149994,281.399994,285.049988,278.102234,40765708,NaN,NaN,NaN,NaN
4,2021-01-07,289.000000,291.799988,287.000000,287.700012,280.687683,30546600,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
565,2023-04-17,528.000000,545.000000,528.000000,544.000000,544.000000,32476990,522.599999,532.404998,550.81350,56.442560
566,2023-04-18,545.349976,548.500000,540.500000,545.849976,545.849976,22283456,524.014998,532.251998,551.27150,62.528734
567,2023-04-19,544.000000,547.500000,538.250000,540.299988,540.299988,21156372,524.804997,532.510998,551.66700,68.227400
568,2023-04-20,541.200012,545.450012,536.650024,544.799988,544.799988,25588577,525.554997,532.844998,552.06975,68.464696
569,2023-04-21,545.000000,546.400024,539.700012,543.150024,543.150024,22599418,526.752498,532.823998,552.49000,70.212766

In [65]:
# making RSI
# def RSI(data: pd.DataFrame, period:int):
change = (data['Close'] - data["Open"])
data["gain"] = change.where(change > 0, 0)
# print(gain)
data["loss"] = change.where(change < 0 , 0)
data["loss"] = data["loss"].abs()
data["av gain"] = data["gain"].rolling(14).mean()
data["av loss"] = data["loss"].rolling(14).mean()

rs = data["av gain"] / data["av loss"]
# print(rs)
data["RSI"] = 100 - (100 / (1 + rs))
data.drop(['gain', 'loss', 'av gain', 'av loss'], axis = 1)
data.tail(50)

,Date,Open,High,Low,Close,Adj Close,Volume,MA20,MA50,MA200,RSI,gain,loss,av gain,av loss
520,2023-02-06,558.799988,558.799988,536.549988,545.400024,545.400024,25338586,575.210004,594.126002,536.594001,18.219266,0.000000,13.399964,2.053571,9.217856
521,2023-02-07,548.000000,551.400024,541.049988,547.099976,547.099976,16195947,572.180002,592.896002,536.748001,19.340730,0.000000,0.900024,2.053571,8.564287
522,2023-02-08,550.000000,554.500000,545.500000,549.750000,549.750000,15502847,569.910001,591.720002,536.993751,19.903079,0.000000,0.250000,2.053571,8.264287
523,2023-02-09,552.000000,552.000000,542.799988,550.799988,550.799988,15061047,567.614999,590.687002,537.274001,19.896194,0.000000,1.200012,2.053571,8.267857
524,2023-02-10,546.500000,557.250000,546.500000,553.049988,553.049988,13824475,565.522498,589.586002,537.511750,23.619930,6.549988,0.000000,2.521428,8.153573
525,2023-02-13,554.000000,556.900024,533.299988,537.500000,537.500000,18488732,562.392499,588.185002,537.713000,20.335351,0.000000,16.500000,2.382141,9.332145
526,2023-02-14,539.950012,544.599976,530.750000,540.849976,540.849976,18559909,559.284998,586.656002,537.879750,21.990339,0.899964,0.000000,2.446424,8.678571
527,2023-02-15,540.000000,544.650024,536.799988,542.250000,542.250000,12796579,556.749997,585.322002,538.109500,27.894495,2.250000,0.000000,2.607139,6.739288
528,2023-02-16,546.849976,546.849976,538.500000,540.099976,540.099976,12767016,554.182495,583.983002,538.355000,33.318068,0.000000,6.750000,2.607139,5.217861
529,2023-02-17,538.500000,539.650024,527.750000,531.000000,531.000000,14192008,551.239996,582.370001,538.611750,29.864985,0.000000,7.500000,2.449995,5.753575
530,2023-02-20,532.000000,533.950012,522.150024,525.150024,525.150024,12570032,547.887497,580.543002,538.837500,22.791465,0.000000,6.849976,1.842852,6.242859
531,2023-02-21,527.099976,528.950012,522.400024,523.450012,523.450012,10223218,544.037497,578.751002,539.035000,31.159383,0.000000,3.649964,1.842852,4.071424
532,2023-02-22,520.750000,521.900024,512.500000,516.349976,516.349976,14763050,540.137497,576.743002,539.237250,22.572485,0.000000,4.400024,1.278569,4.385712
533,2023-02-23,516.950012,524.000000,511.350006,521.000000,521.000000,15535085,537.752496,574.653002,539.466250,18.296683,4.049988,0.000000,0.982139,4.385712
534,2023-02-24,524.200012,527.500000,517.599976,521.049988,521.049988,12253035,536.807495,572.755001,539.688750,21.186360,0.000000,3.150024,0.982139,3.653573
535,2023-02-27,521.099976,529.799988,519.000000,527.700012,527.700012,11048799,536.282495,571.242002,540.014000,28.824338,6.600036,0.000000,1.453570,3.589286
536,2023-02-28,527.250000,528.450012,521.049988,522.799988,522.799988,15768010,534.747495,569.609001,540.404750,27.205855,0.000000,4.450012,1.453570,3.889287
537,2023-03-01,523.250000,537.400024,523.099976,536.700012,536.700012,13510198,535.214996,568.254001,540.813250,38.828251,13.450012,0.000000,2.414285,3.803571
538,2023-03-02,535.950012,539.900024,532.500000,533.750000,533.750000,10376913,535.497498,567.061001,541.145500,32.950418,0.000000,2.200012,1.946429,3.960715
539,2023-03-03,542.000000,564.299988,541.750000,561.200012,561.200012,27656538,536.347498,566.417001,541.661501,54.391099,19.200012,0.000000,3.317858,2.782144
540,2023-03-06,564.900024,567.900024,559.000000,561.700012,561.700012,16162268,537.162497,566.171001,542.232501,51.938439,0.000000,3.200012,3.253575,3.010716
541,2023-03-08,560.000000,565.500000,556.450012,564.799988,564.799988,12637578,538.047498,565.525001,542.744501,53.296403,4.799988,0.000000,3.435717,3.010716
542,2023-03-09,564.750000,565.750000,558.000000,558.900024,558.900024,8993423,538.504999,564.665001,543.234501,53.833259,0.000000,5.849976,3.435717,2.946429
543,2023-03-10,553.099976,554.950012,545.000000,547.349976,547.349976,11522371,538.332498,563.591001,543.661001,54.908694,0.000000,5.750000,3.435717,2.821429
544,2023-03-13,547.000000,553.150024,528.450012,530.000000,530.000000,14373729,537.179999,561.955001,544.040501,49.207168,0.000000,17.000000,3.435717,3.546430
545,2023-03-14,527.650024,532.799988,520.000000,525.400024,525.400024,14750800,536.575000,560.189001,544.323001,49.922146,0.000000,2.250000,3.435717,3.446433
546,2023-03-15,529.799988,532.000000,515.549988,517.549988,517.549988,11282329,535.410001,558.296001,544.566001,46.161231,0.000000,12.250000,3.435717,4.007145
547,2023-03-16,518.400024,529.349976,514.299988,524.500000,524.500000,20040008,534.522501,556.538000,544.815501,47.199996,6.099976,0.000000,3.582145,4.007145
548,2023-03-17,528.650024,531.599976,520.099976,529.799988,529.799988,18787379,534.007501,555.030000,545.124001,49.208622,1.149964,0.000000,3.664285,3.782144
549,2023-03-20,526.599976,526.599976,515.000000,519.200012,519.200012,14275315,533.417502,553.312001,545.378501,42.551150,0.000000,7.399964,3.192854,4.310713
550,2023-03-21,522.000000,523.450012,516.450012,521.849976,521.849976,29485180,533.252499,551.736000,545.638501,44.367224,0.000000,0.150024,3.192854,4.003571
551,2023-03-22,522.200012,527.000000,520.099976,521.549988,521.549988,11619538,533.157498,550.012999,545.923750,35.531503,0.000000,0.650024,2.232139,4.050001
552,2023-03-23,519.400024,521.000000,511.500000,512.750000,512.750000,22097792,532.977499,548.364999,546.169000,33.820295,0.000000,6.650024,2.232139,4.367859
553,2023-03-24,514.500000,514.950012,503.450012,505.350006,505.350006,14416984,532.195000,546.537999,546.378750,14.632588,0.000000,9.149994,0.860709,5.021430
554,2023-03-27,507.000000,514.150024,501.549988,510.149994,510.149994,15674218,531.650000,544.842998,546.573000,18.468937,3.149994,0.000000,1.085709,4.792858
555,2023-03-28,511.450012,511.750000,503.850006,508.100006,508.100006,15833599,530.670000,543.002999,546.778750,12.863254,0.000000,3.350006,0.742852,5.032144
556,2023-03-29,509.000000,518.000000,506.299988,516.500000,516.500000,24203789,530.355000,541.272999,547.052000,21.696898,7.500000,0.000000,1.278567,4.614288
557,2023-03-31,520.650024,524.900024,519.349976,523.750000,523.750000,17356345,529.707500,539.888998,547.441500,26.299216,3.099976,0.000000,1.499994,4.203574
558,2023-04-03,524.750000,528.500000,522.099976,526.750000,526.750000,14210949,529.357500,538.594998,547.834750,35.466352,2.000000,0.000000,1.642851,2.989288
559,2023-04-05,527.000000,527.599976,519.049988,523.000000,523.000000,13574801,527.447499,537.257999,548.193000,34.534427,0.000000,4.000000,1.642851,3.114288
560,2023-04-06,524.000000,533.700012,521.650024,527.650024,527.650024,25125879,525.745000,535.966999,548.623250,45.948186,3.650024,0.000000,1.903567,2.239288
561,2023-04-10,529.250000,530.400024,524.400024,526.299988,526.299988,17335453,523.820000,534.483998,549.049750,37.465735,0.000000,2.950012,1.467854,2.450003
562,2023-04-11,530.849976,535.700012,527.150024,532.099976,532.099976,26414406,522.479997,533.238998,549.536750,37.579578,1.250000,0.000000,1.475000,2.450003
563,2023-04-12,533.200012,534.000000,526.000000,528.200012,528.200012,21292441,521.522499,532.428998,549.924000,39.295839,0.000000,5.000000,1.475000,2.278577
564,2023-04-13,529.299988,534.250000,527.150024,532.950012,532.950012,28597560,521.670000,532.288998,550.350500,43.354120,3.650024,0.000000,1.735716,2.267861
565,2023-04-17,528.000000,545.000000,528.000000,544.000000,544.000000,32476990,522.599999,532.404998,550.813500,56.442560,16.000000,0.000000,2.878573,2.221431
566,2023-04-18,545.349976,548.500000,540.500000,545.849976,545.849976,22283456,524.014998,532.251998,551.271500,62.528734,0.500000,0.000000,2.914287,1.746429
567,2023-04-19,544.000000,547.500000,538.250000,540.299988,540.299988,21156372,524.804997,532.510998,551.667000,68.227400,0.000000,3.700012,2.914287,1.357145
568,2023-04-20,541.200012,545.450012,536.650024,544.799988,544.799988,25588577,525.554997,532.844998,552.069750,68.464696,3.599976,0.000000,2.946429,1.357145
569,2023-04-21,545.000000,546.400024,539.700012,543.150024,543.150024,22599418,526.752498,532.823998,552.490000,70.212766,0.000000,1.849976,2.946429,1.250000

In [66]:
def RSI(change : pd.Series, period: int):
    gain = change.where(change > 0, 0)
    loss = change.where(change < 0 , 0)
    loss = loss.abs()
    avgain = gain.rolling(period).mean()
    avloss = loss.rolling(period).mean()
    rs = avgain / avloss
    rsi = 100 - (100 / (1 + rs))
    return rsi

In [67]:
data["RSI"] = RSI(data['Close']-data["Open"], 14)

In [62]:
type(data['Close']-data["Open"])

pandas.core.series.Series